[project]
name = "capstone-reciclagemcorreta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jw-trindade", email = "trindade2888@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "pygame-ce>=2.5.8",
    "pymunk>=7.3.0",
    "streamlit>=1.64.0",
]

[project.scripts]
capstone-reciclagemcorreta = "capstone_reciclagemcorreta:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
